[package]
name = "call2fa-rust-sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
reqwest = { version = "0.12.22", features = ["blocking", "json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
thiserror = "2.0.12"
